name: "default"
seed: 42
epochs: 100

# """
# pattern
# "null":標準
# "a":画像を水平反転
# "b":画像を回転
# "c":ランダムクロップ
# "d": ランダムアージング
# """
transform:
  pattern: null #abcdを並び変えて設定

dataloader:
  batch_size: 256

# type
# 0:最初の
# 10:畳み込み層を増加
# 1:MaxPoolを増加
# 2:1と2
model:
  type: 0
  enc_dim: 128

optimizer:
  name: Adam  # SGD,Adam
  lr: 1.0e-2
  weight_decay: 0 #1.0e-4

scheduler:
  name: ReduceLROnPlateau #ReduceLROnPlateau  CosineAnnealingLR  None

